import type { AppConfig } from "../types";

export const DEFAULT_APP_CONFIG: AppConfig = {
  backend_type: "ollama",
  base_url: "http://localhost:11434",
  model: "llama2",
  api_key: null,
  api_keys: null,
  system_prompt: null,
  theme: null,
  primary_color: null,
  temperature: null,
  max_tokens: null,
  agent_workspace_path: null,
  openwebui_api_path: "/api",
  openwebui_enable_tools: true,
  openwebui_enable_rag: false,
  openwebui_workspace: null,
  feature_flags: {
    "agent.runtimeV2.enabled": true,
    "agent.planner.capabilityAware": true,
    "agent.tools.parallel.enabled": true,
    "agent.tools.maxParallel.enabled": true,
  },
  runtime_profile: "default",
  knowledge_index_mode: "sqlite_fts",
  mcp_servers: [],
  tool_policy: {
    role: "owner",
    mode: "confirm_all",
    allowed_tools: null,
    denied_tools: null,
    require_confirmation_for: ["run_shell_command"],
  },
  enabled_skills: [],
  skill_auto_recommend: true,
  skill_trust_modes: {},
  agent_templates: [],
  agent_profiles: [],
  active_agent_profile_id: null,
  agent_groups: [],
  active_agent_group_id: null,
  workspaces: [],
  active_workspace_id: null,
  scheduled_tasks: [],
  browser_command_bridge_enabled: false,
  browser_command_bridge_url: "http://127.0.0.1:4317",
  browser_command_bridge_token: null,
  theme_tokens: null,
};
